import React from 'react';
import {
  AccessPointNetwork,
  Account,
  AirFilter,
  Alarm,
  Battery,
  Battery10,
  Battery20,
  Battery30,
  Battery40,
  Battery50,
  Battery60,
  Battery70,
  Battery80,
  Battery90,
  BatteryCharging,
  BatteryCharging10,
  BatteryCharging20,
  BatteryCharging30,
  BatteryCharging40,
  BatteryCharging50,
  BatteryCharging60,
  BatteryCharging70,
  BatteryCharging80,
  BatteryCharging90,
  BatteryChargingWireless,
  BatteryChargingWireless10,
  BatteryChargingWireless20,
  BatteryChargingWireless30,
  BatteryChargingWireless40,
  BatteryChargingWireless50,
  BatteryChargingWireless60,
  BatteryChargingWireless70,
  BatteryChargingWireless80,
  BatteryChargingWireless90,
  BatteryHeartVariant,
  BatteryMinus,
  BatteryPlus,
  Bluetooth,
  Brightness1,
  Brightness2,
  Brightness3,
  Brightness4,
  Brightness5,
  Brightness6,
  Brightness7,
  Cast,
  Cellphone,
  CheckboxMarkedCircleOutline,
  DoorClosed,
  DoorOpen,
  Eye,
  Fan,
  FanChevronUp,
  Flash,
  FormatListBulleted,
  Google,
  GoogleDownasaur,
  Harddisk,
  Home,
  Leak,
  LedOff,
  LedOn,
  LedStripVariant,
  Lightbulb,
  LightbulbGroup,
  LightbulbGroupOutline,
  LightbulbOutline,
  Map,
  MotionSensor,
  MotionSensorOff,
  Palette,
  Phone,
  PineTree,
  PowerPlug,
  PowerPlugOff,
  PowerSocketUs,
  RaspberryPi,
  Remote,
  Restart,
  RollerShade,
  RollerShadeClosed,
  Scent,
  ScriptText,
  Sim,
  Television,
  Thermometer,
  Timelapse,
  Timer,
  TimerOutline,
  ToggleSwitch,
  Update,
  UsbPort,
  Vibrate,
  VolumeOff,
  Water,
  WaterOff,
  WaterPercent,
  WeatherCloudy,
  WeatherSunny,
  WifiStrength1,
  WifiStrength2,
  WifiStrength3,
  WifiStrength4,
  WifiStrengthOff,
  WifiStrengthOutline,
  WindowClosed,
  WindowClosedVariant,
  WindowOpen,
  WindowOpenVariant,
} from 'mdi-material-ui';

const hassMappings = {
  'mdi:access-point-network': AccessPointNetwork,
  'mdi:account': Account,
  'mdi:air-filter': AirFilter,
  'mdi:alarm': Alarm,
  'mdi:battery': Battery,
  'mdi:battery-10': Battery10,
  'mdi:battery-20': Battery20,
  'mdi:battery-30': Battery30,
  'mdi:battery-40': Battery40,
  'mdi:battery-50': Battery50,
  'mdi:battery-60': Battery60,
  'mdi:battery-70': Battery70,
  'mdi:battery-80': Battery80,
  'mdi:battery-90': Battery90,
  'mdi:battery-charging': BatteryCharging,
  'mdi:battery-charging-10': BatteryCharging10,
  'mdi:battery-charging-20': BatteryCharging20,
  'mdi:battery-charging-30': BatteryCharging30,
  'mdi:battery-charging-40': BatteryCharging40,
  'mdi:battery-charging-50': BatteryCharging50,
  'mdi:battery-charging-60': BatteryCharging60,
  'mdi:battery-charging-70': BatteryCharging70,
  'mdi:battery-charging-80': BatteryCharging80,
  'mdi:battery-charging-90': BatteryCharging90,
  'mdi:battery-charging-wireless': BatteryChargingWireless,
  'mdi:battery-charging-wireless-10': BatteryChargingWireless10,
  'mdi:battery-charging-wireless-20': BatteryChargingWireless20,
  'mdi:battery-charging-wireless-30': BatteryChargingWireless30,
  'mdi:battery-charging-wireless-40': BatteryChargingWireless40,
  'mdi:battery-charging-wireless-50': BatteryChargingWireless50,
  'mdi:battery-charging-wireless-60': BatteryChargingWireless60,
  'mdi:battery-charging-wireless-70': BatteryChargingWireless70,
  'mdi:battery-charging-wireless-80': BatteryChargingWireless80,
  'mdi:battery-charging-wireless-90': BatteryChargingWireless90,
  'mdi:battery-heart-variant': BatteryHeartVariant,
  'mdi:battery-minus': BatteryMinus,
  'mdi:battery-plus': BatteryPlus,
  'mdi:bluetooth': Bluetooth,
  'mdi:brightness-1': Brightness1,
  'mdi:brightness-2': Brightness2,
  'mdi:brightness-3': Brightness3,
  'mdi:brightness-4': Brightness4,
  'mdi:brightness-5': Brightness5,
  'mdi:brightness-6': Brightness6,
  'mdi:brightness-7': Brightness7,
  'mdi:cast': Cast,
  'mdi:cellphone': Cellphone,
  'mdi:checkbox-marked-circle-outline': CheckboxMarkedCircleOutline,
  'mdi:device_tracker': Account,
  'mdi:door-closed': DoorClosed,
  'mdi:door-open': DoorOpen,
  'mdi:eye': Eye,
  'mdi:fan': Fan,
  'mdi:fan-chevron-up': FanChevronUp,
  'mdi:flash': Flash,
  'mdi:format-list-bulleted': FormatListBulleted,
  'mdi:google': Google,
  'mdi:google-downasaur': GoogleDownasaur,
  'mdi:harddisk': Harddisk,
  'mdi:home': Home,
  'mdi:leak': Leak,
  'mdi:led-on': LedOn,
  'mdi:led-off': LedOff,
  'mdi:led-strip-variant': LedStripVariant,
  'mdi:lightbulb': Lightbulb,
  'mdi:lightbulb-group': LightbulbGroup,
  'mdi:lightbulb-group-outline': LightbulbGroupOutline,
  'mdi:lightbulb-outline': LightbulbOutline,
  'mdi:map': Map,
  'mdi:motion-sensor': MotionSensor,
  'mdi:motion-sensor-off': MotionSensorOff,
  'mdi:palette': Palette,
  'mdi:phone': Phone,
  'mdi:pine-tree': PineTree,
  'mdi:power-plug': PowerPlug,
  'mdi:power-plug-off': PowerPlugOff,
  'mdi:power-socket-us': PowerSocketUs,
  'mdi:remote': Remote,
  'mdi:raspberry-pi': RaspberryPi,
  'mdi:restart': Restart,
  'mdi:scent': Scent,
  'mdi:script-text': ScriptText,
  'mdi:sim': Sim,
  'mdi:television': Television,
  'mdi:thermometer': Thermometer,
  'mdi:timelapse': Timelapse,
  'mdi:timer': Timer,
  'mdi:timer-outline': TimerOutline,
  'mdi:toggle-switch': ToggleSwitch,
  'mdi:update': Update,
  'mdi:usb-port': UsbPort,
  'mdi:vibrate': Vibrate,
  'mdi:volume-off': VolumeOff,
  'mdi:water': Water,
  'mdi:water-off': WaterOff,
  'mdi:water-percent': WaterPercent,
  'mdi:weather-cloudy': WeatherCloudy,
  'mdi:weather-sunny': WeatherSunny,
  'mdi:wifi-strength-1': WifiStrength1,
  'mdi:wifi-strength-2': WifiStrength2,
  'mdi:wifi-strength-3': WifiStrength3,
  'mdi:wifi-strength-4': WifiStrength4,
  'mdi:wifi-strength-off': WifiStrengthOff,
  'mdi:wifi-strength-outline': WifiStrengthOutline,
  'mdi:window-closed': WindowClosed,
  'mdi:window-closed-variant': WindowClosedVariant,
  'mdi:window-open': WindowOpen,
  'mdi:window-open-variant': WindowOpenVariant,
  'mdi:roller-shade-closed': RollerShadeClosed,
  'mdi:roller-shade': RollerShade,
};

export default function Icon({ icon, ...props }) {
  const Icon = hassMappings[icon] || GoogleDownasaur;
  if (typeof icon !== 'string') {
    console.log(icon);
  }
  if (!hassMappings[icon] && icon?.startsWith('mdi:')) {
    console.log(`Icon not found "${icon}"`);
  }
  return <Icon {...props} />;
}
