import React from 'react';
import {
  AccessPointNetwork as AccessPointNetworkIcon,
  Account as AccountIcon,
  AirFilter as AirFilterIcon,
  Alarm as AlarmIcon,
  Battery as BatteryIcon,
  Battery10 as Battery10Icon,
  Battery20 as Battery20Icon,
  Battery30 as Battery30Icon,
  Battery40 as Battery40Icon,
  Battery50 as Battery50Icon,
  Battery60 as Battery60Icon,
  Battery70 as Battery70Icon,
  Battery80 as Battery80Icon,
  Battery90 as Battery90Icon,
  BatteryCharging as BatteryChargingIcon,
  BatteryCharging10 as BatteryCharging10Icon,
  BatteryCharging20 as BatteryCharging20Icon,
  BatteryCharging30 as BatteryCharging30Icon,
  BatteryCharging40 as BatteryCharging40Icon,
  BatteryCharging50 as BatteryCharging50Icon,
  BatteryCharging60 as BatteryCharging60Icon,
  BatteryCharging70 as BatteryCharging70Icon,
  BatteryCharging80 as BatteryCharging80Icon,
  BatteryCharging90 as BatteryCharging90Icon,
  BatteryChargingWireless as BatteryChargingWirelessIcon,
  BatteryChargingWireless10 as BatteryChargingWireless10Icon,
  BatteryChargingWireless20 as BatteryChargingWireless20Icon,
  BatteryChargingWireless30 as BatteryChargingWireless30Icon,
  BatteryChargingWireless40 as BatteryChargingWireless40Icon,
  BatteryChargingWireless50 as BatteryChargingWireless50Icon,
  BatteryChargingWireless60 as BatteryChargingWireless60Icon,
  BatteryChargingWireless70 as BatteryChargingWireless70Icon,
  BatteryChargingWireless80 as BatteryChargingWireless80Icon,
  BatteryChargingWireless90 as BatteryChargingWireless90Icon,
  BatteryHeartVariant as BatteryHeartVariantIcon,
  BatteryMinus as BatteryMinusIcon,
  BatteryPlus as BatteryPlusIcon,
  Bluetooth as BluetoothIcon,
  Brightness1 as Brightness1Icon,
  Brightness2 as Brightness2Icon,
  Brightness3 as Brightness3Icon,
  Brightness4 as Brightness4Icon,
  Brightness5 as Brightness5Icon,
  Brightness6 as Brightness6Icon,
  Brightness7 as Brightness7Icon,
  Cast as CastIcon,
  Cellphone as CellphoneIcon,
  CheckboxMarkedCircleOutline as CheckboxMarkedCircleOutlineIcon,
  DoNotDisturb as DoNotDisturbIcon,
  DoorClosed as DoorClosedIcon,
  DoorOpen as DoorOpenIcon,
  Eye as EyeIcon,
  Fan as FanIcon,
  FanChevronUp as FanChevronUpIcon,
  Flash as FlashIcon,
  FormatListBulleted as FormatListBulletedIcon,
  Google as GoogleIcon,
  GoogleDownasaur as GoogleDownasaurIcon,
  GoogleHome as GoogleHomeIcon,
  Harddisk as HarddiskIcon,
  Home as HomeIcon,
  Leak as LeakIcon,
  LedStripVariant as LedStripVariantIcon,
  Lightbulb as LightbulbIcon,
  LightbulbGroup as LightbulbGroupIcon,
  Map as MapIcon,
  MotionSensor as MotionSensorIcon,
  MotionSensorOff as MotionSensorOffIcon,
  Palette as PaletteIcon,
  Phone as PhoneIcon,
  PineTree as PineTreeIcon,
  PowerPlug as PowerPlugIcon,
  PowerPlugOff as PowerPlugOffIcon,
  PowerSocketUs as PowerSocketUsIcon,
  Remote as RemoteIcon,
  Restart as RestartIcon,
  ScriptText as ScriptTextIcon,
  Sim as SimIcon,
  Television as TelevisionIcon,
  Thermometer as ThermometerIcon,
  Timelapse as TimelapseIcon,
  Timer as TimerIcon,
  TimerOutline as TimerOutlineIcon,
  ToggleSwitch as ToggleSwitchIcon,
  Update as UpdateIcon,
  UsbPort as UsbPortIcon,
  Vibrate as VibrateIcon,
  VolumeOff as VolumeOffIcon,
  Water as WaterIcon,
  WaterOff as WaterOffIcon,
  WaterPercent as WaterPercentIcon,
  WeatherCloudy as WeatherCloudyIcon,
  WeatherSunny as WeatherSunnyIcon,
  WifiStrength1 as WifiStrength1Icon,
  WifiStrength2 as WifiStrength2Icon,
  WifiStrength3 as WifiStrength3Icon,
  WifiStrength4 as WifiStrength4Icon,
  WifiStrengthOff as WifiStrengthOffIcon,
  WifiStrengthOutline as WifiStrengthOutlineIcon,
  WindowClosed as WindowClosedIcon,
  WindowClosedVariant as WindowClosedVariantIcon,
  WindowOpen as WindowOpenIcon,
  WindowOpenVariant as WindowOpenVariantIcon,
} from 'mdi-material-ui';

const hassMappings = {
  'mdi:access-point-network': AccessPointNetworkIcon,
  'mdi:account': AccountIcon,
  'mdi:air-filter': AirFilterIcon,
  'mdi:alarm': AlarmIcon,
  'mdi:battery': BatteryIcon,
  'mdi:battery-10': Battery10Icon,
  'mdi:battery-20': Battery20Icon,
  'mdi:battery-30': Battery30Icon,
  'mdi:battery-40': Battery40Icon,
  'mdi:battery-50': Battery50Icon,
  'mdi:battery-60': Battery60Icon,
  'mdi:battery-70': Battery70Icon,
  'mdi:battery-80': Battery80Icon,
  'mdi:battery-90': Battery90Icon,
  'mdi:battery-charging': BatteryChargingIcon,
  'mdi:battery-charging-10': BatteryCharging10Icon,
  'mdi:battery-charging-20': BatteryCharging20Icon,
  'mdi:battery-charging-30': BatteryCharging30Icon,
  'mdi:battery-charging-40': BatteryCharging40Icon,
  'mdi:battery-charging-50': BatteryCharging50Icon,
  'mdi:battery-charging-60': BatteryCharging60Icon,
  'mdi:battery-charging-70': BatteryCharging70Icon,
  'mdi:battery-charging-80': BatteryCharging80Icon,
  'mdi:battery-charging-90': BatteryCharging90Icon,
  'mdi:battery-charging-wireless': BatteryChargingWirelessIcon,
  'mdi:battery-charging-wireless-10': BatteryChargingWireless10Icon,
  'mdi:battery-charging-wireless-20': BatteryChargingWireless20Icon,
  'mdi:battery-charging-wireless-30': BatteryChargingWireless30Icon,
  'mdi:battery-charging-wireless-40': BatteryChargingWireless40Icon,
  'mdi:battery-charging-wireless-50': BatteryChargingWireless50Icon,
  'mdi:battery-charging-wireless-60': BatteryChargingWireless60Icon,
  'mdi:battery-charging-wireless-70': BatteryChargingWireless70Icon,
  'mdi:battery-charging-wireless-80': BatteryChargingWireless80Icon,
  'mdi:battery-charging-wireless-90': BatteryChargingWireless90Icon,
  'mdi:battery-heart-variant': BatteryHeartVariantIcon,
  'mdi:battery-minus': BatteryMinusIcon,
  'mdi:battery-plus': BatteryPlusIcon,
  'mdi:bluetooth': BluetoothIcon,
  'mdi:brightness-1': Brightness1Icon,
  'mdi:brightness-2': Brightness2Icon,
  'mdi:brightness-3': Brightness3Icon,
  'mdi:brightness-4': Brightness4Icon,
  'mdi:brightness-5': Brightness5Icon,
  'mdi:brightness-6': Brightness6Icon,
  'mdi:brightness-7': Brightness7Icon,
  'mdi:cast': CastIcon,
  'mdi:cellphone': CellphoneIcon,
  'mdi:checkbox-marked-circle-outline': CheckboxMarkedCircleOutlineIcon,
  'mdi:device_tracker': AccountIcon,
  'mdi:do-not-disturb': DoNotDisturbIcon,
  'mdi:door-closed': DoorClosedIcon,
  'mdi:door-open': DoorOpenIcon,
  'mdi:eye': EyeIcon,
  'mdi:fan': FanIcon,
  'mdi:fan-chevron-up': FanChevronUpIcon,
  'mdi:flash': FlashIcon,
  'mdi:format-list-bulleted': FormatListBulletedIcon,
  'mdi:google': GoogleIcon,
  'mdi:google-downasaur': GoogleDownasaurIcon,
  'mdi:google-home': GoogleHomeIcon,
  'mdi:harddisk': HarddiskIcon,
  'mdi:home': HomeIcon,
  'mdi:leak': LeakIcon,
  'mdi:led-strip-variant': LedStripVariantIcon,
  'mdi:lightbulb': LightbulbIcon,
  'mdi:lightbulb-group': LightbulbGroupIcon,
  'mdi:map': MapIcon,
  'mdi:motion-sensor': MotionSensorIcon,
  'mdi:motion-sensor-off': MotionSensorOffIcon,
  'mdi:palette': PaletteIcon,
  'mdi:phone': PhoneIcon,
  'mdi:pine-tree': PineTreeIcon,
  'mdi:power-plug': PowerPlugIcon,
  'mdi:power-plug-off': PowerPlugOffIcon,
  'mdi:power-socket-us': PowerSocketUsIcon,
  'mdi:remote': RemoteIcon,
  'mdi:restart': RestartIcon,
  'mdi:script-text': ScriptTextIcon,
  'mdi:sim': SimIcon,
  'mdi:television': TelevisionIcon,
  'mdi:thermometer': ThermometerIcon,
  'mdi:timelapse': TimelapseIcon,
  'mdi:timer': TimerIcon,
  'mdi:timer-outline': TimerOutlineIcon,
  'mdi:toggle-switch': ToggleSwitchIcon,
  'mdi:update': UpdateIcon,
  'mdi:usb-port': UsbPortIcon,
  'mdi:vibrate': VibrateIcon,
  'mdi:volume-off': VolumeOffIcon,
  'mdi:water': WaterIcon,
  'mdi:water-off': WaterOffIcon,
  'mdi:water-percent': WaterPercentIcon,
  'mdi:weather-cloudy': WeatherCloudyIcon,
  'mdi:weather-sunny': WeatherSunnyIcon,
  'mdi:wifi-strength-1': WifiStrength1Icon,
  'mdi:wifi-strength-2': WifiStrength2Icon,
  'mdi:wifi-strength-3': WifiStrength3Icon,
  'mdi:wifi-strength-4': WifiStrength4Icon,
  'mdi:wifi-strength-off': WifiStrengthOffIcon,
  'mdi:wifi-strength-outline': WifiStrengthOutlineIcon,
  'mdi:window-closed': WindowClosedIcon,
  'mdi:window-closed-variant': WindowClosedVariantIcon,
  'mdi:window-open': WindowOpenIcon,
  'mdi:window-open-variant': WindowOpenVariantIcon,
};

export default function Icon({ icon, ...props }) {
  const Icon = hassMappings[icon] || GoogleDownasaurIcon;
  if (!hassMappings[icon] && icon?.startsWith('mdi:')) {
    console.log(`Icon not found "${icon}"`);
  }
  return <Icon {...props} />;
}
