const FAN_SUPPORT_SET_SPEED = 1;
const FAN_SUPPORT_OSCILLATE = 2;
const FAN_SUPPORT_DIRECTION = 4;

const LIGHT_SUPPORT_BRIGHTNESS = 1;
const LIGHT_SUPPORT_COLOR = 16;

export {
  FAN_SUPPORT_SET_SPEED,
  FAN_SUPPORT_OSCILLATE,
  FAN_SUPPORT_DIRECTION,
  LIGHT_SUPPORT_BRIGHTNESS,
  LIGHT_SUPPORT_COLOR,
};
